pubdb/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pubdb.views.home', name='home'),

    url(r'^pubview/', include('pubview.urls', namespace ='pubview')),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

pubview/urls.py
from django.conf.urls import patterns, url
from django.views.generic import DetailView, ListView
from pubview import views
from pubview.models import Vote, Paper

urlpatterns = patterns('',
    url(r'^$',
	ListView.as_view(
		queryset=Paper.objects.order_by('-year')[:5],
		context_object_name='latest_paper_list',
		template_name='pubview/index.html'),
	name = 'index'),
    url(r'^(?P<pk>\d+)/$',
	DetailView.as_view(
		model = Paper,
		template_name = 'pubview/detail.html'),
	 name='detail'),
    url(r'^(?P<paper_id>\d+)/vote/$', views.vote, name='vote'),
)

pubview/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Journal(models.Model):
	# journals have names, ...?
	# linked to papers via Paper model

        name = models.CharField(max_length=1000)

	#
	# functions
	#
	def __unicode__(self):
		return self.name

	
class Paper(models.Model):
    # paper is collection of PaperVersions
    # need to keep title, year, abstract
    # linked to authors via Author
    
    title = models.CharField(max_length=1000)
    journal = models.ForeignKey(Journal)
    year = models.IntegerField()
    abstract = models.CharField(max_length = 100000)
    volume = models.IntegerField(default = -1)
    number = models.IntegerField(default = -1)
    startpage = models.IntegerField(default =-1)
    endpage = models.IntegerField(default = -1)
    #
    # functions
    #
    def __unicode__(self):
        return self.title
    #
    # get the authors
    #
    def get_authors(self):
        toreturn = []
        for a in self.author_set.all():
            toreturn.append(a.__unicode__())
        return ", ".join(toreturn)
    
    def get_citation(self):
        return '%s, %s' % (self.journal, self.year)

class PaperVersion(models.Model):
	# need to be able to keep multiple versions of papers, e.g. arXiv version, published version
	# maybe don't need to keep the title here?
	# keep all the other meta-info? (e.g. volume, number, etc)
        paper = models.ForeignKey(Paper)
        journal = models.ForeignKey(Journal)
        year = models.IntegerField()
        title = models.CharField(max_length=1000)
	
	#
	# functions
	#
	def __unicode__(self):
		return self.title

class Author(models.Model):
	# authors linked to paper and coauthors

	firstname = models.CharField(max_length=500)
	lastname = models.CharField(max_length=500)
	papers = models.ManyToManyField(Paper)
	coauthors = models.ManyToManyField('self')
	#
	# functions
	#
	def __unicode__(self):
		toreturn = " ".join([self.firstname, self.lastname])
		return toreturn



class Account(models.Model):
	#
	# account can upvote/downvote
	#
	user = models.OneToOneField(User)
	votes = models.ManyToManyField(Paper, through='Vote')
	def __unicode__(self):
		return self.user.__unicode__()
        def alreadyvoted(self, pid):
		# has this account voted on this paper?
		v = self.votes.filter(pk = pid)
		if len(v) < 1:
			return False
		else:
			return True		

class Vote(models.Model):
        VOTE_TYPES = (
                ('U', 'Up'),
                ('D', 'Down'),
		('I', 'Irrelevant'),
        )
        account = models.ForeignKey(Account)
        paper = models.ForeignKey(Paper)
        votetype = models.CharField(max_length = 1, choices = VOTE_TYPES)

class Topic(models.Model):
	name = models.CharField(max_length = 1000)
	papers = models.ManyToManyField(Paper, through = 'PaperMembership')

class PaperMembership(models.Model):
	MEMBERSHIP_TYPES = (
		('C', 'Core'),
		('N', 'NonCore'),
	)
	paper = models.ForeignKey(Paper)
	topic = models.ForeignKey(Topic)
	membership_type = models.CharField(max_length = 1, choices = MEMBERSHIP_TYPES)
	

pubview/views.py
# Create your views here.

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import Context, loader
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404
from pubview.models import Paper, Account, Vote

def index(request):
    a = request.user.account
    latest_paper_list = Paper.objects.all().order_by('-year')[:5]
    context = {'latest_paper_list': latest_poll_list}
    return render(request, 'pubview/index.html', context)

@login_required
def vote(request, paper_id):
    p = get_object_or_404(Paper, pk=paper_id)
    try:
        v = Vote(account = request.user.account, paper = p, votetype = request.POST['votetype'])
    except (KeyError, Vote.DoesNotExist):
        # Redisplay the poll voting form.
        return render(request, 'pubview/detail.html', {
            'paper': p,
            'error_message': "Vote type doesn't exist",
        })
    else: #has this user already voted on this paper?
        if not request.user.account.alreadyvoted(paper_id): # save if not
            v.save()
        else:
            # is the vote the same?
            testv = Vote.objects.get(account = request.user.account, paper = p)
            if testv.votetype != v.votetype:
                testv.votetype = v.votetype
                testv.save()
            # Always return an HttpResponseRedirect after successfully dealing
            # with POST data. This prevents data from being posted twice if a
            # user hits the Back button.
            return HttpResponseRedirect(reverse('pubview:index'))

def list_unvoted_papers(request):
    pass
    ListView.as_view(
		queryset=Paper.objects.order_by('-year')[:5],
		context_object_name='latest_paper_list',
		template_name='pubview/index.html')

pubview/templates/pubview/detail.html
User: {{user.username}}
<h1>{{ paper.title }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<p>
{{paper.abstract}}
<form action="{% url 'pubview:vote' paper.id %}" method="post">
{% csrf_token %}

<input type="radio" name="votetype" id="1" value="U" />
<label for="choice1">Upvote</label><br />
<input type="radio" name="votetype" id="2" value="D" />
<label for="choice2">Downvote</label><br />
<input type="submit" value="Vote" />
</form>
</p>

pubview/templates/pubview/index.html
{% load staticfiles %}
<head>
  <link rel="stylesheet" type="text/css" href='/static/pubview/css/bootstrap.min.css' />
  <link rel="stylesheet" type="text/css" href="{% static 'pubview/css/style.css' %}" />
  <script type="text/javascript" src="/static/pubview/js/jquery-2.0.0.min.js"></script>
  <script type="text/javascript" src="/static/pubview/js/bootstrap.min.js"></script>
  <title>{% block title %}Recent publications{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script>
    $(document).ready(function(){
      $('.tt').tooltip()
    });
  </script>
</head>

<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="brand" href="#">PubView</a>
        <div class="nav-collapse collapse">
          <ul class="nav">
            <li class="active"><a href="#">My Page</a></li>
            <li><a href="#add_topic" data-toggle="modal">Add New Topic</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="hero-unit">
    <h1>Welcome to PubView!</h1>
  </div>
  
  {% block content %}
  User: {{user.username}}
  <br/><br/>
  <div class='row-fluid'>
    <div class='offset1 span10'>
      <ul class='nav nav-tabs'>
        <li class='active'><a href="#unvoted_papers" data-toggle="tab">New papers</a></li>
        <li><a href="#liked_papers" data-toggle="tab">Liked papers</a></li>
        <li><a href="#disliked_papers" data-toggle="tab">Disliked papers</a></li>
      </ul>
      <div class='tab-content'>
        <div class='tab-pane active' id='unvoted_papers'>
          {% if latest_paper_list %}
          <ol>
            {% for paper in latest_paper_list %}
            <div class="list">
              <a href="{% url 'pubview:detail' paper.id %}" class='tt' data-toggle='tooltip' title="{{ paper.abstract }}" data-placement='right'>{{ paper.title }}</a>
              <br/>
              {{paper.get_citation}}, {{paper.get_authors}}<br/>
              <button name="votetype" id="1" value="U" class='btn btn-success'><i class="icon-arrow-up icon-white"></i> Like</button>
              <button name="votetype" id="2" value="D" class='btn btn-danger'><i class="icon-arrow-down icon-white"></i> Dislike</button>
              <button name="votetype" id="2" value="D" class='btn'>Not interested</button>
              <form action="{% url 'pubview:vote' paper.id %}" method="post"> {% csrf_token %}
              </form>
            </div>
            {% endfor %}
          </ol>
          {% else %}
            <p>No new papers are available.</p>
          {% endif %}
        </div>
        <div class='tab-pane' id='liked_papers'>
          {% if voted_paper_list %}
          {% else %}
            <p>You have not liked any papers yet.</p>
          {% endif %}
        </div>
        <div class='tab-pane' id='disliked_papers'>
          {% if voted_paper_list %}
          {% else %}
            <p>You have not disliked any papers yet.</p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>  
  <div id="add_topic" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="add_topic_label" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
      <h3 id="add_topic_label">Choose topic to add...</h3>
    </div>
    <div class="modal-body">
      <input type="text" class='span3'   data-provide="typeahead" style="margin: 0 auto;" autocomplete='off' data-source='["Population Genetics", "eQTLs"]' />
      <br/>
    </div>
    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
      <button class="btn btn-primary">Add Topic</button>
    </div>
  </div>
  {% endblock %}
</body>